[platformio]
default_envs = nanoatmega328
src_dir = .

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<*>
  -<tests/>
  -<docs/>
  -<.github/>
lib_ldf_mode = deep+
lib_ignore =
  LiquidCrystal
lib_deps =
  ../Samovar/libraries/iarduino_I2C_connect
  ../Samovar/libraries/GyverStepper
  ../Samovar/libraries/GyverEncoder
  ../Samovar/libraries/PinChangeInterrupt
  ../Samovar/libraries/TimerOne
  ../Samovar/libraries/LiquidMenu
  ../Samovar/libraries/LiquidCrystal_I2C2
  ../Samovar/libraries/ArduinoTrace
  ../Samovar/libraries/SoftI2CMaster
build_flags =
  -I../Samovar/libraries/LiquidCrystal_I2C2
  -I../Samovar/libraries/SoftI2CMaster/src
